version: '3.8'

services:
  fastify:
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/cnab"
      PORT: "3333"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cnab

    ports:
      - 5432:5432
